apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "database"
    vaultSkipTLSVerify: "true"
    objects:  |
      array:
        - |
          objectPath: "/db-pass"
          objectName: "password"
          objectVersion: ""
