kind: Pod
apiVersion: v1
metadata:
  name: issues
  labels:
    app: issues
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "issues-app"
    vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
    vault.hashicorp.com/agent-inject-template-database-config.txt: |
      {{- with secret "internal/data/database/config" -}}
      postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@postgres:5432/wizard
      {{- end -}}
spec:
  # This service account does not have permission to request the secrets.
  serviceAccountName: issues-app
  containers:
  - image: jweissig/app:0.0.1
    name: issues